package utils

const (
	CLASSNAME_Object                        = "java/lang/Object"
	CLASSNAME_System                        = "java/lang/System"
	CLASSNAME_Cloneable                     = "java/lang/Cloneable"
	CLASSNAME_Serializable                  = "java/io/Serializable"
	CLASSNAME_VM                            = "sun/misc/VM"
	CLASSNAME_Class                         = "java/lang/Class"
	CLASSNAME_prim_double                   = "double"
	CLASSNAME_prim_long                     = "long"
	CLASSNAME_prim_float                    = "float"
	CLASSNAME_prim_int                      = "int"
	CLASSNAME_prim_char                     = "char"
	CLASSNAME_prim_short                    = "short"
	CLASSNAME_prim_byte                     = "byte"
	CLASSNAME_prim_boolean                  = "boolean"
	CLASSNAME_prim_void                     = "void"
	CLASSNAME_Unsafe                        = "sun/misc/Unsafe"
	CLASSNAME_Reflection                    = "sun/reflect/Reflection"
	CLASSNAME_AccessController              = "java/security/AccessController"
	CLASSNAME_Thread                        = "java/lang/Thread"
	CLASSNAME_ThreadGroup                   = "java/lang/ThreadGroup"
	CLASSNAME_Field                         = "java/lang/reflect/Field"
	CLASSNAME_String                        = "java/lang/String"
	CLASSNAME_Constructor                   = "java/lang/reflect/Constructor"
	CLASSNAME_NativeConstructorAccessorImpl = "sun/reflect/NativeConstructorAccessorImpl"
	CLASSNAME_AtomicLong                    = "java/util/concurrent/atomic/AtomicLong"
	CLASSNAME_Signal                        = "sun/misc/Signal"
	CLASSNAME_FileOutputStream              = "java/io/FileOutputStream"
	CLASSNAME_FileInputStream               = "java/io/FileInputStream"
	CLASSNAME_Runtime                       = "java/lang/Runtime"
	CLASSNAME_UnixFileSystem                = "java/io/UnixFileSystem"
	CLASSNAME_URLClassPath                  = "sun/misc/URLClassPath"
	CLASSNAME_ClassLoader                   = "java/lang/ClassLoader"
	CLASSNAME_Locale                        = "java/util/Locale"

	METHODNAME_InitializeSystemClass = "initializeSystemClass"
	METHODNAME_Initialize            = "initialize"
	METHODNAME_Init                  = "<init>"
)
